### ISSUE TITLE
Import `namify` in `DynamicSymTypes.jl`

### ISSUE THREAD

**Issue by jlapeyre** [JuliaDynamics/DynamicSumTypes.jl#102]
In order to compile and use `DynamicSumTypes` without the deprecated code, I find I have to insert this near the top of  `DynamicSumTypes.jl`
```julia
using MacroTools: namify
```
If I then comment out including the deprecated code, and remove `ExprTools` from Project.toml,  all tests pass.

This allows one to explore the code more easily without the cruft.

Main branch:  23a52b486

**Comment by Tortar** [comment]
yes, thanks, I didn't thought about it. I plan to remove the deprecated code not too far in the future. I mainly added it because we supported the previous version in Agents.jl, but hopefully this could be removed as soon as people have the time to adapt to the new methodology
