### ISSUE TITLE
Consider removing support for duplicated variants

### ISSUE THREAD

**Issue by jlapeyre** [JuliaDynamics/DynamicSumTypes.jl#104]
For example `@sumtype A(Int, Int)`
names the two variants `Int1` and `Int2`. But there is no way to distinguish which variant you are instantiating or which variant is present.

Maybe there is a use case I'm missing, but I can't think of one. If it does make sense to remove support, erroring with an appropriate message seems like a good idea.

**Comment by Tortar** [comment]
yes, in the case you are mentioning it doesn't make sense and the macro should error, but consider:

```
struct B{T} x::T end

@sumtype A(B{Int}, B{Float64})
```

also in this case we have

```julia
julia> allvariants(A)
(B1 = B{Int64}, B2 = B{Float64})
```

but also, probably it is better to instead have something like


```julia
julia> allvariants(A)
(B_Int = B{Int64}, B_Float64 = B{Float64})
```

probably?
