### ISSUE TITLE
@pattern breaks incremental compilation

### ISSUE THREAD

**Issue by xlxs4** [JuliaDynamics/DynamicSumTypes.jl#71]
Not sure if you were aware, didn't find any caveat mentioned.

I'm trying to incorporate `@pattern` in a package, and it works great, but loading extensions now fails. Offending line is https://github.com/JuliaDynamics/DynamicSumTypes.jl/blob/5dc034e2a0aecff79622da9634bc513966639703/src/Pattern.jl#L64

```julia-repl
ERROR: LoadError: InitError: Evaluation into the closed module `FooModule` breaks incremental 
compilation because the side effects will not be permanent. This is likely due to some other 
module mutating `FooModule` with `eval` during precompilation - don't do this.
```

**Comment by Tortar** [comment]
Ouch, this is bad. I worked hard to avoid this kind of problems in 1.0 but I didn't considered package extensions :(

If you give me some pseudocode on what you are doing I'll understand if this is fixable or not. If you are trying to use pattern on the same sum type you defined in the package I unfortunately think you're out of luck at least until someone explains to me if what I describe here is safe: https://discourse.julialang.org/t/is-using-base-delete-method-on-user-defined-functions-safe/115194 . That would allow extending pattern function on signatures already defined in a modile outside the module they were defined. This should definetely go in a caveats section.

If you instead are using pattern on a function signature (variants of the same type are actually working on the same signature) which wasn't already defined in the package, and it doesn't work, this is definetely a fixable bug with the techniques I'm using currently.

Maybe I will try to bump again the topic on discourse in the hope of a definite answer

**Comment by Tortar** [comment]
I'm also thinking that the offending line is probably buggy in the case of extensions, so this could be fixable if pattern is used on a new function signature in the extensions :-)

**Comment by xlxs4** [comment]
Cool, thanks for the quick reply! A MWE of what I'm doing I think would be along those lines:

```julia
# package
module DSS

using DynamicSumTypes

DynamicSumTypes.@sum_structs Foo begin
    struct VariantA
        x::Float64
    end
    struct VariantB
        x::Float64
        y::Float64
    end
end

@pattern foo(v::VariantA) = v.x
@pattern foo(v::VariantB) = v.x + v.y

function bar()
    v = [VariantA(1), VariantB(2,3)]
    return map(foo, v)
end

function ext end

export bar

end # module DSS
```

```julia
# extension
module DSSExt

using DSS

DSS.ext() = 1

end # module DSSExt
```

**Comment by Tortar** [comment]
thank you, I will try to replicate this as soon as I find the time. The last reply to my post on discourse made me realize that loading the final function at `__init__` time is not good...so stay tuned for a breaking release :D 

This will just require to add a `define_pattern_functions!()` at the end of the module, so it shouldn't be too bad. In the meantime I will definitely fix this and add #70 to the mix. 

For now I think you could stick with `kindof` branches, I should be able to make a new release this week anyway

**Comment by Tortar** [comment]
I pushed some changes to the repo, I tried to reproduce setting up a little package with your code and I couldn't reproduce any failure. So maybe it's okay? Could  you try to use the dev version on your real code to see if it now works? You now need to put `define_pattern_functions()` at the end of your module

**Comment by Tortar** [comment]
Sorry you should use `finalize_patterns()` instead of `define_pattern_functions()`...always undecided about names :D

**Comment by xlxs4** [comment]
That was quick. Works like a charm, thanks a lot!

**Comment by Tortar** [comment]
@xlxs4 if you can take a final look at the final version of the repo, and that everything still works correctly, I will release 2.0 just after that :-)

In practice I changed again the way to register the pattern functions :D, because doing with a macro is better not to pollute other modules: so now it is `@finalize_patterns`

Also now variants are accessible only from the type e.g. `T'.Variant`, if you want to re-establish previous behaviour you can use `@export_variants(T)`

**Comment by Tortar** [comment]
in particular the last commit I pushed one min ago is crucial for the performance of pattern, finger crossed that everything is okay

**Comment by Tortar** [comment]
ok I now tried your MWE with the updated code for 2.0

```julia
module DSS

using DynamicSumTypes

DynamicSumTypes.@sum_structs Foo begin
    struct VariantA
        x::Float64
    end
    struct VariantB
        x::Float64
        y::Float64
    end
end

export_variants(Foo)

@pattern foo(v::VariantA) = v.x
@pattern foo(v::VariantB) = v.x + v.y

function bar()
    v = [VariantA(1), VariantB(2,3)]
    return map(foo, v)
end

function ext end

export bar

@finalize_patterns

end # module DSS
```

```julia
# extension
module DSSExt

using DSS

DSS.ext() = 1

end # module DSSExt
```

and...it didn't worked first try but after one last fix it finally worked!

**Comment by xlxs4** [comment]
It works!

**Comment by Tortar** [comment]
FYI DynamicSumTypes 2.0 should be now available
