### ISSUE TITLE
Method definition errors dependiong on how the package is imported

### ISSUE THREAD

**Issue by nandoconde** [JuliaDynamics/DynamicSumTypes.jl#95]
Hello!

First of all, thanks for the package. I see the future of Enums and Sum Types in Julia in the direction this is going.

I detected that using this package breaks at runtime depending on how it is imported. MWE is:

```
julia> import DynamicSumTypes: @sumtype
julia> struct A end
julia> struct B end
julia> @sumtype AB(A,B)
ERROR: UndefVarError: `DynamicSumTypes` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: a global variable of this name also exists in DynamicSumTypes.
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/DynamicSumTypes/TMnLE/src/DynamicSumTypes.jl:45
```

I belive the reason is the way methods are `eval`ed at runtime, because of `@sumtype` macro definition. Particularly, lines 45, 69, 70 and 71 of https://github.com/JuliaDynamics/DynamicSumTypes.jl/blob/main/src/DynamicSumTypes.jl, which try to define methods of the `variant`, `variantof`, `allvariants` and `is_sumtype` into `DynamicSumTypes` module, and it may not exist. This breaks precompilation at least, and directly breaks at runtime if the package was not imported with `using`.

Also, function `variantof` is redefined everytime `@sumtype` is called, because it redefines the method `variantof(Any)`.

I can try to come up with a PR for the latter problem, but the solution tot he first eludes me, because I know nothing about metaprogramming and macros.

Thanks in advance!

**Comment by Tortar** [comment]
thanks for reporting this, I was a bit too lazy with hygiene stuff :-)

**Comment by Tortar** [comment]
should be fixed by #96

**Comment by Tortar** [comment]
Actually there are still some problems with the exported functions even if now the mwe works

**Comment by nandoconde** [comment]
Thanks, so fast!

Yeah, the export seemed tricky to me, I don't know how to solve it :(

Anyway, I can test the package as soon as the new version is released. It may be good to create specific tests for it?

**Comment by Tortar** [comment]
Actually everything works, I was tricked by the Julia import system :D

**Comment by Tortar** [comment]
> It may be good to create specific tests for it?

yes, It would be a good addition, if you want to contribute it would be very welcomed! Otherwise no problem.

If you want to test it even if still unreleased you can also `]dev` it
