### ISSUE TITLE
Better automatic enum-like properties

### ISSUE THREAD

**Issue by nandoconde** [JuliaDynamics/DynamicSumTypes.jl#98]
Hello!

I am starting to use this package to define several structures in my own package that fit the use case quite well. However, I find that some tooling that I construct around the sum types I create could be created programmatically when defined. These are:

1. Member discoverability at REPL
2. Instance constructors (for sum-type "members", not of variant types)
3. Named access to original types

I will sketch out the implementations I do, and we can discuss whether they are worth it and if it is the best way to implement them.

## Basic definitions

Assuming the following sum types:
```julia
import Base
using DynamicSumTypes

struct A end

struct B
   i::Int
   j::Int
end

struct C
   c::Char
end

@sumtype ABC(A,B,C)
```

## Member discoverability at REPL

```julia
Base.propertynames(::Type{ABC}) = (:A, :B, :C)

# julia> ABC.<TAB>
# A
# B
# C
```

## Instance constructors

```julia
# Instance constuctors
function Base.getproperty(::Type{ABC}, s::Symbol)
    if s == :A
        return (x...) -> ABC(A(x...))
    elseif s == :B
        return (x...) -> ABC(B(x...))
    elseif s == :C
        return (x...) -> ABC(C(x...))
    else
        return getfield(ABC, s)
    end
end

# julia> ABC.A()
# ABC(A())
#
# julia> ABC.B(9,8)
# ABC(B(9,8))
#
# julia> ABC.C('c')
# ABC(C('c'))
```

## Named access to original types
```julia
# This should replace the current definition of allvariants(::Type{ABC})
allvariants(::Type{ABC}) = (A=A, B=B, C=C)

# julia> allvariants(ABC).A
# A
# This avoids having to know beforehand the place of A in the allvariants:
# julia> allvariants(ABC)[1]
# A
```

**Comment by Tortar** [comment]
Unfortunately 1. and 2. are not possible. I would have really like 2. and I thought about it many times but there is a subtle issue: you will practically create optimization problems with 2. I think, I learnt from here: https://github.com/JuliaLang/julia/discussions/48883#discussioncomment-5362804.

3. is instead a good one I think, it would require a new major version release but I have no problem with that.
 
There is a trick which would allow to implement 2. though:

```julia
Base.adjoint(T::Type{ABC}) = (
     A = (args...) -> constructor(ABC, A, args...), 
     B = (args...) -> constructor(ABC, B, args...), 
     C = (args...) -> constructor(ABC, C, args...)
)

constructor(T, V, args::Vararg{Any, N}) where N = T(V((args...)))
```

so that

```julia
julia> ABC'.B(1,1)
ABC(B(1, 1))
```

**Comment by nandoconde** [comment]
Yeah, a pity about the performance pitfall of 2, I suspected it would not be great because of the closure and the varargs preventing compilation and specialization at creation.

Regarding 1, it is solved directly with the implementation of 3, since (at least in v1.11+) it autocompletes:

```julia
julia> allvariants_new(ABC).<TAB>
A
B
C
```

It may be even worth coming up with a nice syntax to make it shorter, so that 2 can be dropped altogether, and variant creation will be:

```julia
julia> ABC(allvariants(ABC).A())
ABC(A())
julia> ABC(allvariants(ABC).B(8,9))
ABC(B(8,9)
julia> ABC(allvariants(ABC).C('c'))
ABC(C('c'))
```

**Comment by Tortar** [comment]
I have implemented what we have discussed, let me know if you have any suggestion :-)

**Comment by Tortar** [comment]
I will sneak the changes in a minor release because returning a namedtuple while strictly breaking I don't think will be practically so

**Comment by nandoconde** [comment]
Hi! That was fast!

It seems you have implemented the variant constructors directly. I don't want to reduce the speed of the package, I saw the comparison against others and it was very good. Have you tested the performance?
